Add basic, chroma, pinecone retrievers and related tests
hivenetwork-ai/hive-agent-py pull request #46
Opened 2024-07-26 13:24 UTC by umutunsal

2024-07-29 18:27 UTC, ToJen requested changes

2024-07-29 18:27 UTC, ToJen commented on hive_agent/tools/retriever/base_retrieve.py
> +            return "No documents found to insert."
should we raise an error with the error message here instead?

2024-07-29 18:27 UTC, ToJen commented on hive_agent/tools/retriever/pinecone_retrieve.py
> +        self.pinecone_client = Pinecone(api_key=PINECONE_API_KEY)
add API key to **.env.example** file

2024-07-29 18:38 UTC, umutunsal commented
More discussed topics
- Create basic index automatically when /upload documents endpoint called
- Get a parameter to control index store types like full text, hybrid, semantic etc.

2024-07-30 17:50 UTC, umutunsal commented
Except "Get a parameter to control index store types like full text, hybrid, semantic etc." this feature all of them fixed or implemented. Llamaindex chroma integration "stores_text" parameter is not working properly and needs more deep dive.

2024-07-30 18:37 UTC, ToJen submitted a review, later dismissed

2024-07-30 22:04 UTC, ToJen approved these changes

2024-07-31 12:00 UTC, ToJen approved these changes

2024-07-31 13:20 UTC, merged